Translations generated in cockpit-machines repo with make update-po
cockpit-project/cockpit-machines-weblate pull request #1
Opened 2021-03-19 09:32 UTC by KKoukiou

2021-03-19 11:11 UTC, marusak commented on machines.html.pot
> +msgid "Virtual machines management"
Please don't add those partial .pot files

2021-03-19 11:14 UTC, marusak requested changes, later dismissed
Please no partial.pot files and also I think this was generated from cockpit repo but it should be generated from https://github.com/cockpit-project/cockpit-weblate to include also languages that are not translated to 50% and thus not in cockpit repo directly.

2021-03-19 15:03 UTC, KKoukiou commented
> Please no partial.pot files and also I think this was generated from cockpit repo but it should be generated from https://github.com/cockpit-project/cockpit-weblate to include also languages that are not translated to 50% and thus not in cockpit repo directly.

you got it right, did not realize there was this difference!

2021-03-19 16:17 UTC, KKoukiou commented on machines.html.pot
> +msgid "Virtual machines management"
Done.

2021-03-22 08:24 UTC, marusak commented
Looks good, the only issue is that all unused translations are there as well, just commented out. They take 70% of files unnecessary. Can you please remove those? (I guess some mdg* tool will do that with correct option or just you can find the last translated string and delete till the end of file).

2021-03-22 10:30 UTC, marusak approved these changes
Thanks!

2021-03-22 12:36 UTC, merged