Update de.po
cockpit-project/cockpit-machines-weblate pull request #2
Opened 2021-06-11 09:53 UTC by 768kb

Some corrections and suggestions

2021-06-11 10:26 UTC, martinpitt requested changes
Danke! We normally don't edit the .po files directly, but edit translations on https://translate.fedoraproject.org/projects/cockpit-machines/main/de/

Please let me know if you still prefer doing this here, then I'm happy to copy them to weblate once you are done.

Some suggestions, though.

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Speichergrösse darf nicht 0 sein"
It's spelled "Größe" (also in the strings below).

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Die Grösse des Datenträgers darf nicht die Grösse der Storage Pool Kapazität $0 $1 übersteigen"
Please use hyphens, as we do in German: Storage-Pool-Kapazität (plus Größe)

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Das ausgewählte Betriebssystem hat eine minimum Arbeitsspeicher-Anforderung von $0 $1"
"minimale"

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Dieser Datenträger ist bereits in Verwendung einer anderen VM."
This sounds a bit weird IMHO. Maybe "Dieser Datenträger wird bereits von einer anderen VM verwendet."?

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Threads pro Core"
Thanks, "Fäden" is ridiculous, but "Kern" is fine IMHO.

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "trennen"
Please capitalize, "Trennen".

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Bis zu $0 $1 verfügbar in der Standard Lokation"
"Lokation" sounds weird, and hyphens. "im Standard-Ort"? or "Standard-Pool"?

2021-06-11 10:26 UTC, martinpitt commented on de.po
>  #, fuzzy
You need to remove fuzzy flag after updating strings.

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Benutzer Anmeldung"
I'd say, "Benutzername" is clearer here.

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Benutzer Login darf nicht leer sein wenn Passwort gesetzt ist"
Please use a consistent wording here, same as "User login" above. "Benutzername" is our standard term in cockpit.

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Benutzer Passwort"
"Benutzerpasswort" or "Benutzer-Passwort"

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Fehler beim erstellen des Datenträgers"
"E"rstellen

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Datenträger Gruppenname"
IMHO that's too confusing -- "volume group" is an LVM term. Cockpit's German translations use "Datenträgerverbund", but just keeping the term may be less confusing for admins. "Name der Volume-Group"?

2021-06-11 10:26 UTC, martinpitt commented on de.po
> +msgstr "Passwort Qualität"
Hyphen or single word again.

2024-01-22 10:59 UTC, marusak commented
This is out of date. I am closing this mainly as it should be submitted in Weblate. @768kb please let me know if you need help with Weblate.

2024-01-22 10:59 UTC, closed without merging